# Толық дәстүрлі сервер стеки (егер қажет болса)
version: '3.8'

services:
  # Next.js приложение
  app:
    build: 
      context: .
      dockerfile: docker/traditional-server.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/mobframe
      - NEXT_PUBLIC_PAYBOX_MERCHANT_ID=${PAYBOX_MERCHANT_ID}
      - PAYBOX_SECRET_KEY=${PAYBOX_SECRET_KEY}
    depends_on:
      - db
      - redis

  # PostgreSQL база данных
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mobframe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
