[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "mobframe-app"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_PAYBOX_MERCHANT_ID = "${{PAYBOX_MERCHANT_ID}}"
PAYBOX_SECRET_KEY = "${{PAYBOX_SECRET_KEY}}"
NEXT_PUBLIC_SUPABASE_URL = "${{SUPABASE_URL}}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${{SUPABASE_ANON_KEY}}"
